---
apiVersion: v1
kind: Service
metadata:
  name: svc-zabbix-server
  namespace: ${AppNS}
spec:
  #externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port:  10051
    protocol: TCP
    targetPort: 10051
  selector:
    app: zabbix-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-server
  namespace: ${AppNS}
  labels:
    app: zabbix-server
    tier: server
spec:
  serviceName: zabbix-server
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: zabbix-server
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix-server
    spec:
      terminationGracePeriodSeconds: 180
      volumes:
        - name: mnt-externalscripts
          persistentVolumeClaim:
             claimName: pvc-zbx-externalscripts
        - name: mnt-mibs
          persistentVolumeClaim:
             claimName: pvc-zbx-mibs
        - name: mnt-alertscripts
          persistentVolumeClaim:
             claimName: pvc-zbx-alertscripts
        - name: mnt-snmptraps
          persistentVolumeClaim:
             claimName: pvc-zbx-snmptraps
        - name: mnt-modules
          persistentVolumeClaim:
             claimName: pvc-zbx-modules
      containers:
      - image: ${K8SREPO}/zabbix-server-pgsql:alpine-5.4.5
        imagePullPolicy: IfNotPresent
        name: zabbix-server
        ports:
        - containerPort: 10051
          protocol: TCP
        env:
          - name: DB_SERVER_HOST
            value: "${DBHOST}"
          - name: DB_SERVER_PORT
            value: "5432"
          - name: POSTGRES_USER
            value: "${DBUSER}"
          - name: POSTGRES_PASSWORD
            value: "${DBPWD}"
          - name: POSTGRES_DB
            value: "${DBNAME}"
          - name: ZBX_LISTENIP
            value: "0.0.0.0"
          - name: ZBX_LOADMODULE
            value: ""
          - name: ZBX_DEBUGLEVEL
            value: "3"
          - name: ZBX_TIMEOUT
            value: "10"
          - name: ZBX_JAVAGATEWAY_ENABLE
            value: "false"
          - name: ZBX_STARTPOLLERS
            value: "5"
          - name: ZBX_STARTPOLLERSUNREACHABLE
            value: "1"
          - name: ZBX_STARTPINGERS
            value: "3"
          - name: ZBX_STARTHTTPPOLLERS
            value: "1"
          - name: ZBX_STARTTRAPPERS
            value: "5"
          - name: ZBX_ENABLE_SNMP_TRAPS
            value: "true"
          - name: ZBX_VMWARECACHESIZE
            value: "128M"
          - name: ZBX_HOUSEKEEPINGFREQUENCY
            value: "1"
          - name: ZBX_CACHESIZE
            value: "2G"
          - name: ZBX_CACHEUPDATEFREQUENCY
            value: "120"
          - name: ZBX_HISTORYCACHESIZE
            value: "32M"
          - name: ZBX_HISTORYINDEXCACHESIZE
            value: "32M"
          - name: ZBX_TRENDCACHESIZE
            value: "512M"
          - name: ZBX_VALUECACHESIZE
            value: "1G"
          - name: ZBX_LOGSLOWQUERIES
            value: "3000"
          - name: ZBX_STARTPROXYPOLLERS
            value: "2"
          - name: ZBX_STARTLLDPROCESSORS
            value: "4"
          - name: ZBX_STATSALLOWEDIP
            value: "127.0.0.1,10.167.249.16/28,172.25.75.0/24"
          - name: ZBX_STARTREPORTWRITERS
            value: "0"
          - name: ZBX_WEBSERVICEURL
            value: "http://zabbix-web-service:10053/report"
        securityContext:
          allowPrivilegeEsclation: true
          capabilities:
            add:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        volumeMounts:
          - mountPath: "/usr/lib/zabbix/externalscripts"
            name: mnt-externalscripts
          - mountPath: "/var/lib/zabbix/mibs"
            name: mnt-mibs
          - mountPath: "/usr/lib/zabbix/alertscripts"
            name: mnt-alertscripts
          - mountPath: "/var/lib/zabbix/modules"
            name: mnt-modules
          - mountPath: "/var/lib/zabbix/snmptraps"
            name: mnt-snmptraps
      restartPolicy: Always
